### ISSUE TITLE
TextKit 2 Support?

### ISSUE THREAD

**Issue by howlingblast** [CineDev/ParagraphTextKit#3]
I was just wondering if you have any plans to support TextKit 2 or if that makes at all?

Thanks for any insight.

**Comment by CineDev** [comment]
Instead of adding TextKit 2 support, I am currently working on a completely new project that is fundamentally based on TextKit 2. Thanks for asking!

**Comment by howlingblast** [comment]
Looking forward to this until you choose to share!

**Comment by CineDev** [comment]
I am very close to release the first public beta. Yet the war (I am living in Ukraine) forces me to postpone the release time after time.

**Comment by howlingblast** [comment]
I'm sorry to hear about what you have to endure these days. All the best, I'll be watching your progress. Good luck!

🇺🇦✊🏽
